// Lecture20
// let arr = [45, 23, 21]
// arr.map((value) => {
//     console.log(value)
// })
// console.log(arr)

//
// let arr = [45, 23, 21]
// // Array map method
// let a = arr.map((value, index, array) => {
//     console.log(value, index, array)
//     return value + index
// })
// console.log(a)

// Array filter method
// let arr2 = [45, 23, 21, 0, 3, 5]
// let a2 = arr2.filter((a) => {
//   return a < 10
// })
// console.log(a2, arr2)

//Array Reduce method
// let arr3 = [1, 2, 3, 5, 2, 1]
// let newarr3 = arr3.reduce((h1, h2) => {
//     return h1 + h2
// })
// console.log(newarr3)

//
// let arr3 = [1, 2, 3, 5, 2, 1]
// const reduce_func = (h1, h2) => {
//   return h1 + h2
// }
// let newarr3 = arr3.reduce(reduce_func)
// console.log(newarr3)


//Leture 21: Chapter 5 Practice Set--------------------
// Practice Problem 1
// let arr = [2, 5, 5, 4, 3, 2, 7, 9]
// let a = prompt("Enter a number")
// a = Number.parseInt(a)
// arr.push(a)
// console.log(arr)

// Practice Problem 2
// let arr = [2, 5, 5, 4, 3, 2, 7, 9]
// let a;
// do {
//     a = prompt("Enter a number")
//     a = Number.parseInt(a)
//     arr.push(a)
// } while (a != 0)
// console.log(arr)

// Practice Problem 3
// let arr = [1, 2, 30, 4, 50, 6, 7, 83, 670]
// let n = arr.filter((x) => {
//     return x % 10 == 0
// })
// console.log(n)

// Practice Problem 4
// let arr = [1, 2, 30, 4, 50, 6, 7, 83, 670]
// let n = arr.map((x) => {
//     return x * x
// })
// console.log(n)

// Practice Problem 5
// let arr = [1, 2, 3, 4, 5]
// let n = arr.reduce((x1, x2) => {
//     return x1 * x2
// })
// console.log(n)


//Lecture 22: Exercise 1 Guess the Number--------------------

// let number = 0 // Generate random number here
// let chances = 0
// Keep asking for the number until the correct number is guessed
// Increment the chances variable

// Eventually after the game is over, display the (100 - Number of chances) and the actual number


//Lecture 23: Chapter 6 JavaScript in the Browser--------------------


//Lecture 24: Chapter 6 JavaScript Script Tag--------------
// Advantages of using separate script file using src attribute of script tag
// 1. Separation of concerns
// 2. Browser Caching



//Lecture 25: Chapter 6 JavaScript console object--------------
// console.log("log")
// console.info("info")
// console.warn("warn")
// console.error("err")
// console.assert("err" != false)
// console.assert("err" == false)


// console.time("forLoop")
// for (let i = 0; i < 500; i++) {
//     console.log(233)
// }
// console.timeEnd("forLoop")

// console.time("whileLoop")

// let i = 0;
// while (i < 500) {
//     console.log(233)
//     i++;
// }

// console.timeEnd("whileLoop")


//Lecture 26: JavaScript Exercise 1_solution & Shpoutouts--------------
// let number = Math.floor((Math.random() * 100) + 1); // Generates a random number b/w 1 and 100
// let chances = 0; // Initial vaulue of chances taken to guess a number
// let guess; // Variable to store the number to be input from user to be guessed

// console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win...\n");
// guess = prompt("Enter a number between 1 and 100");
// ++chances; // To increment the number of chances taken

// do {
//     guess = Number.parseInt(guess);

//     if (guess > number) {
//         console.log("Number entered is greater");
//         guess = prompt("Enter again!!");
//         guess = Number.parseInt(guess);
//         ++chances; // To increment the number of chances taken
//         continue;
//     }

//     else if (guess < number) {
//         console.log("Number entered is smaller");
//         guess = prompt("Enter again!!");
//         guess = Number.parseInt(guess);
//         ++chances; //To increment the number of chances taken
//         continue;
//     }

// } while (guess != number); //break the loop if number entered is equal to the number generated

// let score = 100 - chances; //To store the score of your game
// console.log("\nCongratulations🥳🥳\nThe number generated was", number + " and you guessed it right😁\nYour final score is", score);


//Lecture 27: JavaScript alerr, prompt and confirm--------------
// alert("Enter thr value of a!")
// let a = prompt("Enter a here", "578")
// a = Number.parseInt(a)
// alert("You entered a of type " + typeof a)
// let write = confirm("Do you want to write it to the page")
// if (write) {
//     document.write(a)
// }
// else {
//     document.write("Please allow me to write")
// }

//Lecture 28: JavaScript DOM BOM and Window Object------------------
// console.log(window)
// console.log(document.body)
// document.body.style.background = "yellow";


//Lecture 28: JavaScript Chapter6 Practice Set

//Problem 1
// let age = prompt("Enter your Age")
// age = Number.parseInt(age)

// const canDrive = (age) => {
//     return age => 18 ? True : false;
// }

// if (canDrive(age)) {
//     alert("Yes You can drive")
// }
// else {
//     alert("You cannot drive")
// }


//Problem 2
// let runAgain = true;

// const canDrive = (age) => {
//     return age >= 18 ? true : false
// }

// while (runAgain) {
//     let age = prompt("Enter your age")
//     age = Number.parseInt(age)
//     if (age < 0) {
//         console.error("Please enter a valid age");
//         break;
//     }

//     if (canDrive(age)) {
//         alert("Yes you can drive")
//     }
//     else {
//         alert("You cannot drive")
//     }
//     runAgain = confirm("Do you want to play again?")
// }

//Problem 4
// let a = prompt("Enter your number")
// number = Number.parseInt(number)
// if (number > 4) {
//     location.href = "https://google.com"
// }

//Problem 5
// let color = prompt("Enter the page background color")
// document.body.style.background = color

//Lecture 30 Exercise 2
// Create Snake, Water & Gun game in JavaScript.
// The game should ask you to enter S, W or G. The computer should be able to randomly generate S, W or G and declare win or loss using alert
// Use alert, prompt and confirm whereever required!

//Lecture 31: JavaScript Walking Dom--------------------



//Lecture 32: JavaScript Accessing Children of an element--------------------
// console.log(document.body.firstChild)
// console.log(document.body.lastChild)
// let arr = Array.from(document.body.childNodes)
// console.log(arr)


//Lecture 33: JavaScript Parent and sibling of an element--------------------
// console.log(document.body.firstChild)
// a = document.body.firstChild
// console.log(a.parentNode)
// console.log(a.parentElement)
// console.log(a.firstChild.nextSibling)


//Lecture 34: JavaScript Element only Navigation--------------------

// const changeBgRed = () => {
//     document.body.firstElementChild.style.background = "red"
// }

// let b = document.body
// console.log("First child of b is: ", b.firstChild)
// console.log("First Element child of b is: ", b.firstElementChild)

//Lecture 35: JavaScript Table Navigation--------------------
// let t = document.body.firstElementChild.firstElementChild
// console.log(t)
// console.log(t.rows)
// console.log(t.caption)
// console.log(t.tHead.firstElementChild)
// console.log(t.tFoot)
// console.log(t.tBodies)
// console.log(t.rows[1].rowIndex)



//Lecture 36: JavaScript Searching The Dom--------------------
//Change the card tittle red
// let ctitle = document.getElementById("firstcardtitle")
// ctitle.style.color = "blue";

// let ctitles = document.querySelectorAll(".card-title")
// ctitles[0].style.color = "blue"
// ctitles[1].style.color = "red"
// ctitles[2].style.color = "green"
// console.log(ctitles)

// document.querySelector(".this").style.color = "black"
// document.querySelector(".this").style.background = "red"

// console.log(document.getElementsByTagName("a"))
// console.log(document.querySelector(".card").getElementsByTagName("a"))
// console.log(document.getElementsByName("search"))


//Lecture 37:  JavaScript Matches closest and contains--------------------
// let id1 = document.getElementById("id1")
// let sp1 = document.getElementById("sp1")

// console.log(id1)
// console.log(id1.matches(".class"))
// console.log(id1.matches(".box"))
// console.log(sp1.closest("#sp1"))
// console.log(id1.contains(sp1))
// console.log(sp1.contains(sp1))
// console.log(sp1.contains(id1))


//Lecture 38:  JavaScript Chapter7 Practice Set--------------------
// document.getElementsByTagName("nav")[0].firstElementChild.style.color = "red"
// document.getElementsByTagName("nav")[0].firstElementChild.style.color = "green"
// document.getElementsByTagName("nav")[0].lastElementChild.style.color = "green"

// Array.from(document.getElementsByTagName("li")).forEach((element) => {
//     element.style.background = "cyan";
// })

//Lecture 39: JavaScript Exercise 2 _Solutions and Shoutouts---------------
/*
let user = prompt("Enter S, W or G")
let cpuI = Math.floor(Math.random() * 3);
let cpu = ["S", "W", "G"][cpuI]

const match = (cpu, user) => {
    if (cpu === user) {
        return "Nobody"
    }
    else if (cpu === "S" && user === "W") {
        return "cpu"
    }
    else if (cpu === "S" && user === "G") {
        return "user"
    }
    else if (cpu === "G" && user === "W") {
        return "user"
    }
    else if (cpu === "G" && user === "S") {
        return "cpu"
    }
    else if (cpu === "W" && user === "S") {
        return "user"
    }
    else if (cpu === "W" && user === "G") {
        return "cpu"
    }
}
let result = match(cpu, user)
document.write(`CPU:${cpu} <br> User:${user} <br>The winner is: ${result.toUpperCase()}`)
*/


//Lecture 40: JavaScript Exercise 3 _Tell Me A Joke---------------


//Lecture 41: JavaScript innerHTML OuterHTML and other properties---------------------------
// let x = document.getElementsByTagName('span')[0]
// console.log(x)
// let y = document.getElementsByTagName('span')[0]
// console.dir(y)
// console.log(document.body.firstChild.nodeName)
// console.log(document.body.firstElementChild.nodeName)

// first.innerHTML
// first.innerHTML = "<i>hey I am italic</i>"
// first.outerHTML
// // first.outerHTML = "<div>hey</div>"
// document.body.firstChild.data
// console.log(document.body.textContent)
// first.hidden = false


//Lecture 42: JavaScript HTML Attributes and their methods---------------------------
// let first = document.getElementById("first");
// let a = first.getAttribute("class")
// console.log(a)
// console.log(first.hasAttribute("class"))
// console.log(first.hasAttribute("style"))
// first.setAttribute("hidden", "true")
// first.setAttribute("class", "true sachin")
// first.removeAttribute("class")
// console.log(first.attributes)
// console.log(first.dataset)
// console.log(first.dataset.game)
// console.log(first.dataset.player)



//Lecture 43: JavaScript Insertion methods---------------------------
// let a = document.getElementsByTagName('div')[0]

// a.innerHTML = a.innerHTML + '<h1>Hello World!</h1>';

// let div = document.createElement('div');
// div.innerHTML = '<h1>Hello World!</h1>';
// a.append(div);
// a.prepend(div);
// a.before(div);
// a.after(div);
// a.replaceWith(div);


//Lecture 44: JavaScript Insert Adjacents---------------------------
// first.insertAdjacentHTML('beforebegin', '<div class="test">beforebegin</div>');
// first.insertAdjacentHTML('beforeend', '<div class="test">beforeend</div>');
// first.insertAdjacentHTML('afterbegin', '<div class="test">afterbegin</div>');
// first.insertAdjacentHTML('afterend', '<div class="test">afterend</div>');
// first.remove()

//Lecture 45: JavaScript ClassList And ClassName---------------------------
// first.className = "text-black red"
// first.classList.add("red")
// first.classList.remove("red")
// first.classList.contains("red")
// first.classList.toggle("red")